Update advance-scoring3.yaml

diff --git a/.github/workflows/advance-scoring3.yaml b/.github/workflows/advance-scoring3.yaml
--- a/.github/workflows/advance-scoring3.yaml
+++ b/.github/workflows/advance-scoring3.yaml
@@ -105,8 +105,8 @@ jobs:
           opa eval --data policies/vulnerabilities/risk.rego --input input.json "data.policies.vulnerabilities.valid_input" --format=json > valid_input.json
 
           # Output the valid_input.json for debugging
-          echo "valid_input.json:"
-          cat valid_input.json
+          #echo "valid_input.json:"
+          #cat valid_input.json
 
 
             # Evaluate the 'deny_low_score' policy
@@ -124,7 +124,7 @@ jobs:
             echo "------------------------------------------------------------------------------------------------"
 
             
-            # Extract deny_low_score messages and show debug output
+            # Extract deny_low_score messages
             deny_low_score_msgs=$(jq -r '.result[].expressions[].value | if type == "object" and length > 0 then . else empty end' deny_low_score.json)
             
             # Extract keys from the JSON object and count them, ensuring a default value of 0
@@ -134,8 +134,8 @@ jobs:
 
             # Display the count and debug information
             echo "Deny Low Score Count: $deny_low_score_count"
-            echo "Debug - deny_low_score_msgs content:"
-            echo "$deny_low_score_msgs" | jq '.' || echo "Failed to parse deny_low_score_msgs as JSON"
+            #echo "Debug - deny_low_score_msgs content:"
+            #echo "$deny_low_score_msgs" | jq '.' || echo "Failed to parse deny_low_score_msgs as JSON"
 
             # Check if there are any deny low score messages
             if [ "$deny_low_score_count" -gt 0 ]; then
