commit

diff --git a/.github/workflows/advance-scoring2.yaml b/.github/workflows/advance-scoring2.yaml
--- a/.github/workflows/advance-scoring2.yaml
+++ b/.github/workflows/advance-scoring2.yaml
@@ -143,26 +143,20 @@ jobs:
             echo "score_output.json:"
             cat score_output.json
             
-            echo "=============  pass 1"
-
             # Extract deny_low_score messages and show debug output
             deny_low_score_msgs=$(jq -r '.result[].expressions[].value | if type == "object" and length > 0 then . else empty end' deny_low_score.json)
             echo "Debug - Raw deny_low_score.json content:"
             cat deny_low_score.json
-
-            echo "============== pass 2"
 
             # Extract keys from the JSON object and count them, ensuring a default value of 0
             deny_low_score_count=$(echo "$deny_low_score_msgs" | jq 'if . == null or . == "" then 0 else (keys | length) end')
             echo "Debug - deny_low_score_count before conversion: $deny_low_score_count"
             deny_low_score_count=${deny_low_score_count:-0}
 
-            echo "============== pass 3"
-
             # Display the count and debug information
             echo "Deny Low Score Count: $deny_low_score_count"
-            echo "Debug - deny_low_score_msgs content:"
-            echo "$deny_low_score_msgs" | jq '.' || echo "Failed to parse deny_low_score_msgs as JSON"
+            #echo "Debug - deny_low_score_msgs content:"
+            #echo "$deny_low_score_msgs" | jq '.' || echo "Failed to parse deny_low_score_msgs as JSON"
 
             # Check if there are any deny low score messages
             if [ "$deny_low_score_count" -gt 0 ]; then
