Update advance-scoring3.yaml

diff --git a/.github/workflows/advance-scoring3.yaml b/.github/workflows/advance-scoring3.yaml
--- a/.github/workflows/advance-scoring3.yaml
+++ b/.github/workflows/advance-scoring3.yaml
@@ -1,4 +1,4 @@
-name: CI/CD2 with Threagile and Advanced OPA Scoring
+name: CI/CD3 with Threagile and Advanced OPA Scoring
  
 on:
   push:
@@ -109,29 +109,29 @@ jobs:
           #cat valid_input.json
 
           # Check if input is valid
-          valid=$(jq -r '.result[0].expressions[0].value // "false"' valid_input.json)
-          if [ "$valid" != "true" ]; then
-            echo " "
-            echo "------------------------------------------------------------------------------------------------"
-            echo "Input is not valid. Checking for missing risks..."
-            # Evaluate the 'deny_missing_risks' policy
-            opa eval --data policies/vulnerabilities/risk.rego --input input.json "data.policies.vulnerabilities.deny_missing_risks" --format=json > deny_missing_risks.json
+          #valid=$(jq -r '.result[0].expressions[0].value // "false"' valid_input.json)
+          #if [ "$valid" != "true" ]; then
+          #  echo " "
+          #  echo "------------------------------------------------------------------------------------------------"
+          #  echo "Input is not valid. Checking for missing risks..."
+          #  # Evaluate the 'deny_missing_risks' policy
+          #  opa eval --data policies/vulnerabilities/risk.rego --input input.json "data.policies.vulnerabilities.deny_missing_risks" --format=json > deny_missing_risks.json
 
             # Extract deny_missing_risks messages
-            deny_missing_risks_msgs=$(jq -r '.result[0].expressions[0].value | if type == "array" then .[] elif type == "string" then . else empty end' deny_missing_risks.json)
-            deny_missing_risks_count=$(echo "$deny_missing_risks_msgs" | grep -c '^' || echo "0")
+          #  deny_missing_risks_msgs=$(jq -r '.result[0].expressions[0].value | if type == "array" then .[] elif type == "string" then . else empty end' deny_missing_risks.json)
+          #  deny_missing_risks_count=$(echo "$deny_missing_risks_msgs" | grep -c '^' || echo "0")
 
-            echo "Deny Missing Risks Count: $deny_missing_risks_count"
+          #  echo "Deny Missing Risks Count: $deny_missing_risks_count"
 
-            if [ "$deny_missing_risks_count" -gt 0 ]; then
-              echo "OPA Policy Check Failed: 'risks.json' is missing or improperly structured."
-              echo "Deny Missing Risks Messages:"
-              echo "$deny_missing_risks_msgs"
-              exit 1
-            fi
-          else
-            echo "Input is valid. Proceeding to evaluate 'deny_low_score' and 'score_output'..."
-          fi
+          #  if [ "$deny_missing_risks_count" -gt 0 ]; then
+          #    echo "OPA Policy Check Failed: 'risks.json' is missing or improperly structured."
+          #    echo "Deny Missing Risks Messages:"
+          #    echo "$deny_missing_risks_msgs"
+          #    exit 1
+          #  fi
+          #else
+          #  echo "Input is valid. Proceeding to evaluate 'deny_low_score' and 'score_output'..."
+          #fi
 
 
             # Evaluate the 'deny_low_score' policy
