Update gate-testing.yaml

diff --git a/.github/workflows/gate-testing.yaml b/.github/workflows/gate-testing.yaml
--- a/.github/workflows/gate-testing.yaml
+++ b/.github/workflows/gate-testing.yaml
@@ -179,7 +179,7 @@ jobs:
             echo "OPA Policy Check Failed: Detected $deny_count issues."
             # Output each deny message
             jq -r '.result[0].expressions[0].value[]' opa_result.json
-            exit 1
+            exit 1  #actions will show fail because of TEST3 BLOCKING
           else
             echo "OPA Policy Check Passed: No high-severity vulnerabilities detected."
           fi
